version:  '2'
services: 
 nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
    links:
      - tomcatapp1:tomcatapp1
      - tomcatapp2:tomcatapp2
      - tomcatapp3:tomcatapp3
    tomcatapp1:
      image: tomcat
      volumes:
        - sample.war:/usr/local/tomcat/webapps/sample.war
    tomcatapp2:
      image: tomcat
      volumes:
        - sample.war:/usr/local/tomcat/webapps/sample.war
    tomcatapp3:
      image: tomcat
      volumes:
        - sample.war:/usr/local/tomcat/webapps/sample.war
